### PR TITLE
proposal for a new network broadcast interface

### PR DESCRIPTION
**Pull request by ericxtang**
New interface is for network transport layers.  The livepeer node should be able to easily swap in/out video delivery implementations.

### CODE REVIEW

**Review by dob — COMMENTED** [review]
Think we need Unsubscribe as well, otherwise the broadcaster continues to push chunks towards the consumer indefinitely.

**Comment by ericxtang** [comment]
Good point.  I added `Unsubscribe()` and `Finish()`.

**Review by dob — APPROVED** [review]
Cool. I'm not exactly sure about the usage or final semantics of this, but if helpful to merge now then :ship:. I'd imagine we'll be iterating on it depending on needs of the protocol.

**Comment by ericxtang** [comment]
It's more for Scott, so he can have something to program against.  We would use the push-based implementation for Broadcaster and Subscriber, until the PPSPP implementation is ready.

**Pull request merged**
